accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    ]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('reviews/',include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('create/', views.create,name='create'),
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):

    @property
    def full_name(self):
        return f'{self.last_name}{self.first_name}'

reviews/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your views here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=50)
    grade = models.FloatField(validators=[MinValueValidator(0.0),MaxValueValidator(5.0)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',              
                                options={'quality': 80})
    
class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm): # 회원가입시 사용
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2']
        labels = {'username': '아이디', 'password1': '비밀번호', 'password2': '비밀번호확인'}
        #회원 가입시 입력 목록을 명시해주는 것

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        # User 정보 수정 시 사용되며 마찬가지 변경 목록을 지정한것

reviews/forms.py
from django import forms
from .models import Review,Comment

class ReviewForm(forms.ModelForm):
    
    class Meta():
        model = Review
        fields = ['title','content','movie_name','grade','image']
        
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content',]

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from accounts.forms import CustomUserCreationForm

# Create your views here.

def index(request):
    return render(request, 'accounts/index.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user) # 자동 로그인
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/signup.html',context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/login.html',context)
def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

reviews/views.py
from django.shortcuts import render,redirect
from .models import Review,Comment
from .forms import CommentForm, ReviewForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

@login_required
def create(request):
    if request.method == 'POST':
        data = ReviewForm(request.POST)
        if data.is_valid():
            db_data = data.save(commit=False)
            db_data.user = request.user
            db_data.save()
            return redirect('reviews:index')
    else:
        data = ReviewForm()
    return render(request,'reviews/create.html',{'data':data})

def index(request):
    review = Review.objects.all().order_by('-pk')
    page = request.GET.get('page') #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(review, '5') #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
    context = {
        'review':review,
        'page': page_obj,
    }
    return render(request,'reviews/index.html',context)

def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
     
    context = {
        'review':review,
        'comment_form':comment_form,
        'comments': review.comment_set.all(),
    }
    return render(request, 'reviews/detail.html',context)


def comment_create(request,pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    print(comment_form,request.POST)
    if comment_form.is_valid():
        
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)


def comment_delete(request,pk,comment_pk):
    comment = Comment.objects.get(pk = comment_pk)
    if request.user == comment.user: 
        comment.delete()
    return redirect('reviews:detail',pk)

def update(request,pk):
    db_data = Review.objects.get(pk=pk)

    if request.method == 'POST':
        data = ReviewForm(request.POST, instance=db_data)

        if data.is_valid():
            data.save()

            return redirect('reviews:index')

    else:
        data = ReviewForm(instance=db_data)

    return render(request, 'reviews/create.html', {'data': data})

def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()

    return redirect('reviews:index')

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원 목록</h1>
  <a href="{% url 'accounts:signup' %}">회원가입</a>

  {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그아웃</a>

  {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>로그인</h1>

  <form action="{% url 'accounts:login' %}" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" value='로그인'>
  </form>

  <a href="{% url 'accounts:index' %}">Home</a>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>회원 목록</h1>

  <form action="{% url 'accounts:signup' %}" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" value='가입'>
  </form>

  <a href="{% url 'accounts:index' %}">Home</a>

{% endblock %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>생성</h1>
{% else %}
    <h1>수정</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form data %}

    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<a href="{% url 'reviews:index' %}">목록으로</a>
<h1>{{ review.pk }}번 게시글</h1>
<p>작성자 : {{ review.user }}</p>
<p>제목 : {{ review.title }}</p>
<p>내용 : {{ review.content }}</p>
<p>영화 : {{ review.movie_name }}</p>
<p>작성시간 : {{ review.created_at }}</p>
<p>수정시간 : {{ review.updated_at }}</p>
<a href="{% url 'reviews:update' review.pk %}">수정하기</a>
<a href="{% url 'reviews:delete' review.pk %}">삭제하기</a>
{% comment %} 댓글 {% endcomment %}
{% if request.user.is_authenticated %} 
<h4>댓글</h4>
{% if comments %}
<p >{{ comments.count }}개 </p>
{% endif %}

{% if request.user.is_authenticated %}
<form action="{% url 'reviews:comment_create' review.pk %}" method='POST'>
    {% csrf_token %}
  <div class="input-group mb-3">
    <textarea name="content" id="content" rows="2" col="20"></textarea>
    <input type="submit" value="작성">
  </div>
</form>
{% endif %}
{% endif %}
{% for comment in comments %}
{% if request.user == comment.user %}
<a href="{% url 'reviews:comment_delete' review.pk comment.pk %}" class='btn btn-danger float-end'>삭제</a>
{% endif %}
  <div class=''>
    <p > {{ comment.user.username}}님 </p>
    <p>{{ comment.content }}</p>
  </div>
  <hr>
  <br>

  {%empty%}
  <p>댓글이 없어요 ㅠ_ㅠ</p>
{% endfor %}
</div>

{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  <h1 class="text-center mb-5">Movies</h1>
  <table class="table align-middle">
    <thead>
      <tr>
        <th scope="col">NO</th>
        <th scope="col">Title</th>
        <th scope="col">Movie Name</th>
        <th scope="col">Created</th>
        <th scope="col">Updated</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <!-- 넘겨받은 페이지 객체만큼 반복한다. -->
      {% for reviews in page %}
        <tr>
          <td class="fw-bold">
            {{ forloop.counter }}
          </td>
          <td>
            <a class="text-decoration-none text-dark" href="{% url 'reviews:detail' reviews.pk %}">
              {{ reviews.title }}
            </a>
          </td>
          <td>{{ reviews.movie_name }}</td>
          <td>{{ reviews.created_at }}</td>
          <td>{{ reviews.updated_at }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="d-flex justify-content-end">
    <a href="{% url 'reviews:create' %}">
      <button type="button" class="btn btn-primary mb-3">New Movie</button>
    </a>
  </div>
  <!-- 페이징처리 시작 -->
  <nav aria-label="pagination" class="d-flex justify-content-center">
    <ul class="pagination">
      <!-- previous -->
      {% if page.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
      {% endif %}

      <!-- pages -->
      <!-- page.paginator.page_range : [1, ..., max] -->
      {% for i in page.paginator.page_range %}
        {% if i == page.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ i }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      <!-- next -->
      {% if page.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  <!-- 페이징처리 끝 -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    #footer {
      position: fixed;
      bottom: 0;
      width: 100%;
      height: 70px;

    }
  </style>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="">
          <img src="{% static 'frankenstein.png' %}" width="30" height="24" class="d-inline-block align-text-top">
          Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">게시판</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:index' %}">회원목록</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container p-5">
      {% block content %}{% endblock %}
    </div>
    <div id='footer'>
      <footer class="p-3 bg-dark text-white text-center">
        <p>
          django Reviews PJT, by 박태호 신우철</p>
      </footer>
    </div>

  </body>

</html>